# Generated by Django 5.1.4 on 2025-01-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='sharer',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='accounts',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='Sharer',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
