# Generated by Django 5.1.4 on 2025-01-02 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_votes',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('accounts', 'artwork'), name='unique_vote'),
        ),
    ]
