# Generated by Django 5.1.4 on 2025-01-29 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_count', models.PositiveIntegerField(default=1)),
                ('tap_timestamp', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to=settings.AUTH_USER_MODEL)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='app.artwork')),
            ],
        ),
        migrations.DeleteModel(
            name='Sharer',
        ),
    ]
