# Generated by Django 5.1.4 on 2025-01-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tap_unique_tap'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tap',
            name='unique_tap',
        ),
        migrations.RemoveField(
            model_name='tap',
            name='tap_count',
        ),
    ]
