# Generated by Django 5.1.4 on 2025-01-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_votes_leaderboard_total_taps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='total_taps',
            new_name='taps',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='total_votes',
            new_name='votes',
        ),
    ]
