# Generated by Django 5.1.4 on 2025-01-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_total_taps_leaderboard_taps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='artwork_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='artwork_image',
            field=models.ImageField(blank=True, null=True, upload_to='leaderboard_artworks/'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='artwork_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
